# Generated by Django 4.2.7 on 2023-12-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(to='news.post'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
