# Generated by Django 4.2.7 on 2023-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_posts_delete_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts',
            new_name='favorite_posts',
        ),
    ]
