# Generated by Django 4.2.7 on 2024-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='post/files/'),
            preserve_default=False,
        ),
    ]
